import { useState } from "react";
import { ConvexProvider, useAction, useMutation, useQuery } from "convex/react";
import { BrowserRouter, Routes, Route, NavLink } from "react-router-dom";
import { convex } from "./convex";
// @ts-ignore - This will be generated by Convex when you run `npx convex dev`
import { api } from "./convex/_generated/api";
import SearchBox from "./components/SearchBox";
import ResultCard from "./components/ResultCard";
import Dashboard from "./components/Dashboard";
import LiveFeedPage from "./pages/LiveFeedPage";
import ContentPage from "./pages/ContentPage";
import MarketsPage from "./pages/MarketsPage";
import { motion, AnimatePresence } from "framer-motion";
import { Search, BarChart3, Newspaper, BookOpen, Coins } from "lucide-react";

function LiveRunTimeline({ runId }: { runId: string | null }) {
  const events = useQuery(
    // @ts-ignore convex codegen updates after deploy/dev refresh
    api.queries.getRunEvents,
    runId ? { runId: runId as any } : "skip"
  ) as any[] | undefined;

  if (!runId || !events || events.length === 0) {
    return (
      <div className="text-[#888] text-sm">Initializing run...</div>
    );
  }

  return (
    <div className="w-full max-w-xl space-y-2">
      {events.slice(-6).map((event: any, idx: number) => (
        <div key={`${event._id || idx}`} className="flex items-center justify-between text-sm border border-[#1a1a1a] rounded px-3 py-2 bg-[#111]">
          <span className="text-white">{event.stage}</span>
          <span className="text-[#888]">{event.message}</span>
        </div>
      ))}
    </div>
  );
}

function Navigation() {
  const navLinkClass = ({ isActive }: { isActive: boolean }) =>
    `flex items-center gap-2 px-4 py-2.5 rounded-md font-medium transition-all ${
      isActive
        ? "bg-[#111] text-white border border-[#2a3441]"
        : "text-[#888] hover:text-white"
    }`;

  return (
    <nav className="sticky top-0 z-50 bg-[#0f1419] border-b border-[#1a1a1a] mb-8">
      <div className="container mx-auto px-4 py-4 max-w-7xl">
        <div className="flex items-center justify-between mb-4">
          <NavLink to="/" className="text-2xl font-bold text-white hover:text-emerald-400 transition-colors">
            QuantumTruth
          </NavLink>
        </div>
        <div className="flex gap-2 bg-[#0a0a0a] border border-[#1a1a1a] rounded-lg p-1 flex-wrap">
          <NavLink to="/" className={navLinkClass} end>
            <Search className="h-4 w-4" />
            Search
          </NavLink>
          <NavLink to="/live-feed" className={navLinkClass}>
            <Newspaper className="h-4 w-4" />
            Live Feed
          </NavLink>
          <NavLink to="/content" className={navLinkClass}>
            <BookOpen className="h-4 w-4" />
            Content
          </NavLink>
          <NavLink to="/dashboard" className={navLinkClass}>
            <BarChart3 className="h-4 w-4" />
            Dashboard
          </NavLink>
          <NavLink to="/markets" className={navLinkClass}>
            <Coins className="h-4 w-4" />
            Markets
          </NavLink>
        </div>
      </div>
    </nav>
  );
}

function SearchPage() {
  const [question, setQuestion] = useState("");
  const [result, setResult] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [showDebug, setShowDebug] = useState(false);
  const [activeRunId, setActiveRunId] = useState<string | null>(null);
  const [lastRunId, setLastRunId] = useState<string | null>(null);
  const factCheck = useAction(api.actions.factCheck.factCheck);
  // @ts-ignore convex codegen updates after deploy/dev refresh
  const createFactCheckRun = useMutation(api.mutations.createFactCheckRun);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!question.trim()) return;

    setLoading(true);
    setResult(null);

    try {
      const runId = await createFactCheckRun({
        question: question.trim(),
        mode: "deep",
        model: null,
      });
      setActiveRunId(runId as string);
      setLastRunId(runId as string);

      const response = await factCheck({ question: question.trim(), mode: "deep", runId: runId as any });
      setResult(response);
      setActiveRunId(null);
    } catch (error) {
      console.error("Error fact-checking:", error);
      setActiveRunId(null);
      setResult({
        error: error instanceof Error ? error.message : "An error occurred",
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -20 }}
      transition={{ duration: 0.3 }}
      className="container mx-auto px-4 py-8 max-w-7xl"
    >
      <div className="max-w-4xl mx-auto">
        <div className="text-center mb-8">
          <p className="text-[#888]">
            Ask a question and get evidence-grounded answers powered by quantum-inspired algorithms
          </p>
        </div>

        <SearchBox
          question={question}
          setQuestion={setQuestion}
          onSubmit={handleSubmit}
          loading={loading}
        />

        <AnimatePresence mode="wait">
          {loading && (
            <motion.div
              key="loading"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="mt-8"
            >
              <div className="flex flex-col items-center justify-center space-y-4">
                <div className="flex items-center justify-center space-x-2">
                  <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-emerald-500"></div>
                  <span className="text-[#888]">
                    Analyzing question and searching markets...
                  </span>
                </div>
                <LiveRunTimeline runId={activeRunId} />
              </div>
            </motion.div>
          )}

          {result && !loading && (
            <motion.div
              key="result"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.3 }}
              className="mt-8"
            >
              {result.error ? (
                <div className="bg-[#1a0a0a] border border-red-900/50 rounded-lg p-4">
                  <p className="text-red-400">{result.error}</p>
                </div>
              ) : (
                <>
                  {import.meta.env.DEV && (
                    <div className="mb-4 flex justify-end">
                      <button
                        onClick={() => setShowDebug(!showDebug)}
                        className="text-sm text-[#888] hover:text-white transition-colors"
                      >
                        {showDebug ? "Hide" : "Show"} Debug
                      </button>
                    </div>
                  )}
                  {lastRunId && (
                    <div className="mb-4">
                      <div className="text-xs text-[#888] mb-2">Run timeline</div>
                      <LiveRunTimeline runId={lastRunId} />
                    </div>
                  )}
                  <ResultCard result={result} showDebug={showDebug} />
                </>
              )}
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </motion.div>
  );
}

function AppRoutes() {
  return (
    <div className="min-h-screen bg-[#0f1419]">
      <Navigation />

      <Routes>
        <Route path="/" element={<SearchPage />} />
        <Route
          path="/live-feed"
          element={
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.3 }}
            >
              <LiveFeedPage />
            </motion.div>
          }
        />
        <Route
          path="/content"
          element={
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.3 }}
            >
              <ContentPage />
            </motion.div>
          }
        />
        <Route
          path="/dashboard"
          element={
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.3 }}
              className="container mx-auto px-4 py-8 max-w-7xl"
            >
              <Dashboard />
            </motion.div>
          }
        />
        <Route
          path="/markets"
          element={
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.3 }}
            >
              <MarketsPage />
            </motion.div>
          }
        />
      </Routes>
    </div>
  );
}

function App() {
  return (
    <ConvexProvider client={convex}>
      <BrowserRouter>
        <AppRoutes />
      </BrowserRouter>
    </ConvexProvider>
  );
}

export default App;
