import { useState } from "react";
import { ConvexProvider, useAction } from "convex/react";
import { convex } from "./convex";
// @ts-ignore - This will be generated by Convex when you run `npx convex dev`
import { api } from "./convex/_generated/api";
import SearchBox from "./components/SearchBox";
import ResultCard from "./components/ResultCard";
import Dashboard from "./components/Dashboard";
import { motion, AnimatePresence } from "framer-motion";
import { Search, BarChart3 } from "lucide-react";

type View = "search" | "dashboard";

function AppContent() {
  const [view, setView] = useState<View>("search");
  const [question, setQuestion] = useState("");
  const [result, setResult] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [showDebug, setShowDebug] = useState(false);
  const factCheck = useAction(api.actions.factCheck.factCheck);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!question.trim()) return;

    setLoading(true);
    setResult(null);

    try {
      const response = await factCheck({ question: question.trim() });
      setResult(response);
    } catch (error) {
      console.error("Error fact-checking:", error);
      setResult({
        error: error instanceof Error ? error.message : "An error occurred",
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#000000]">
      <div className="container mx-auto px-4 py-8 max-w-7xl">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="mb-8"
        >
          <h1 className="text-4xl font-bold text-center mb-2 text-white">
            Polymarket Fact Checker
          </h1>
          <p className="text-center text-[#888] mb-6">
            Ask a question and get evidence-grounded answers from prediction markets
          </p>

          {/* Navigation Tabs - Polymarket Style */}
          <div className="flex justify-center gap-2 bg-[#0a0a0a] border border-[#1a1a1a] rounded-lg p-1 inline-flex mx-auto">
            <button
              onClick={() => setView("search")}
              className={`flex items-center gap-2 px-6 py-2.5 rounded-md font-medium transition-all ${
                view === "search"
                  ? "bg-[#111] text-white border border-[#2a2a2a]"
                  : "text-[#888] hover:text-white"
              }`}
            >
              <Search className="h-4 w-4" />
              Search
            </button>
            <button
              onClick={() => setView("dashboard")}
              className={`flex items-center gap-2 px-6 py-2.5 rounded-md font-medium transition-all ${
                view === "dashboard"
                  ? "bg-[#111] text-white border border-[#2a2a2a]"
                  : "text-[#888] hover:text-white"
              }`}
            >
              <BarChart3 className="h-4 w-4" />
              Dashboard
            </button>
          </div>
        </motion.div>

        {/* Content */}
        <AnimatePresence mode="wait">
          {view === "search" ? (
            <motion.div
              key="search"
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: 20 }}
              transition={{ duration: 0.3 }}
              className="max-w-4xl mx-auto"
            >
              <SearchBox
                question={question}
                setQuestion={setQuestion}
                onSubmit={handleSubmit}
                loading={loading}
              />

              <AnimatePresence mode="wait">
                {loading && (
                  <motion.div
                    key="loading"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    className="mt-8"
                  >
                    <div className="flex items-center justify-center space-x-2">
                      <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-emerald-500"></div>
                      <span className="text-[#888]">
                        Analyzing question and searching markets...
                      </span>
                    </div>
                  </motion.div>
                )}

                {result && !loading && (
                  <motion.div
                    key="result"
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -20 }}
                    transition={{ duration: 0.3 }}
                    className="mt-8"
                  >
                    {result.error ? (
                      <div className="bg-[#1a0a0a] border border-red-900/50 rounded-lg p-4">
                        <p className="text-red-400">{result.error}</p>
                      </div>
                    ) : (
                      <>
                        {import.meta.env.DEV && (
                          <div className="mb-4 flex justify-end">
                            <button
                              onClick={() => setShowDebug(!showDebug)}
                              className="text-sm text-[#888] hover:text-white transition-colors"
                            >
                              {showDebug ? "Hide" : "Show"} Debug
                            </button>
                          </div>
                        )}
                        <ResultCard result={result} showDebug={showDebug} />
                      </>
                    )}
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          ) : (
            <motion.div
              key="dashboard"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              transition={{ duration: 0.3 }}
            >
              <Dashboard />
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}

function App() {
  return (
    <ConvexProvider client={convex}>
      <AppContent />
    </ConvexProvider>
  );
}

export default App;
