import { useState, useRef, useEffect } from "react";
import { ConvexProvider, useAction } from "convex/react";
import { convex } from "./convex";
// @ts-ignore - This will be generated by Convex when you run `npx convex dev`
import { api } from "./convex/_generated/api";
import SearchBox from "./components/SearchBox";
import ResultCard from "./components/ResultCard";
import Dashboard from "./components/Dashboard";
import { motion, AnimatePresence } from "framer-motion";
import { Search, History, Newspaper, Zap, TrendingUp } from "lucide-react";
import RecentQueries from "./components/RecentQueries";
import NewsFeed from "./components/NewsFeed";
import { UI_CONSTANTS } from "./constants";

type View = "search" | "dashboard" | "queries" | "news";

const tabs = [
  { id: "search" as View, label: "Oracle", icon: Search, description: "Fact-check claims" },
  { id: "dashboard" as View, label: "Markets", icon: TrendingUp, description: "Live data" },
  { id: "queries" as View, label: "History", icon: History, description: "Past queries" },
  { id: "news" as View, label: "Feed", icon: Newspaper, description: "Latest news" },
];

function AppContent() {
  const [view, setView] = useState<View>("search");
  const [question, setQuestion] = useState("");
  const [result, setResult] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [showDebug, setShowDebug] = useState(false);
  const factCheck = useAction(api.actions.factCheck.factCheck);
  
  const tabRefs = useRef<{ [key: string]: HTMLButtonElement | null }>({});
  const containerRef = useRef<HTMLDivElement | null>(null);
  const [indicatorStyle, setIndicatorStyle] = useState({ x: 0, width: 0 });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!question.trim()) return;

    setLoading(true);
    setResult(null);

    try {
      const response = await factCheck({ question: question.trim() });
      setResult(response);
    } catch (error) {
      console.error("Error fact-checking:", error);
      setResult({
        error: error instanceof Error ? error.message : "An error occurred",
      });
    } finally {
      setLoading(false);
    }
  };

  // Update indicator position when view changes or window resizes
  useEffect(() => {
    const updateIndicator = () => {
      const activeButton = tabRefs.current[view];
      const container = containerRef.current;
      
      if (activeButton && container) {
        const containerRect = container.getBoundingClientRect();
        const buttonRect = activeButton.getBoundingClientRect();
        
        setIndicatorStyle({
          x: buttonRect.left - containerRect.left,
          width: buttonRect.width,
        });
      }
    };

    updateIndicator();
    window.addEventListener("resize", updateIndicator);
    
    const timeout = setTimeout(updateIndicator, UI_CONSTANTS.TAB_INDICATOR_UPDATE_DELAY);
    
    return () => {
      window.removeEventListener("resize", updateIndicator);
      clearTimeout(timeout);
    };
  }, [view]);

  return (
    <div className="min-h-screen bg-void bg-grid">
      {/* Ambient gradient */}
      <div className="fixed inset-0 bg-radial-accent pointer-events-none" />
      
      {/* Header */}
      <header className="relative z-50 border-b border-subtle">
        <div className="mx-auto px-4 sm:px-6 lg:px-8 max-w-[1800px]">
          <div className="flex items-center justify-between h-16 md:h-20">
            {/* Logo */}
            <div className="flex items-center gap-4">
              <motion.div 
                className="relative"
                whileHover={{ scale: 1.05 }}
                transition={{ type: "spring", stiffness: 400 }}
              >
                <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-cyan to-cyan/60 flex items-center justify-center glow-cyan">
                  <Zap className="w-5 h-5 text-void" />
                </div>
                <motion.div 
                  className="absolute -top-0.5 -right-0.5 w-3 h-3 bg-amber rounded-full"
                  animate={{ scale: [1, 1.2, 1] }}
                  transition={{ duration: 2, repeat: Infinity }}
                />
              </motion.div>
              
              <div>
                <h1 className="font-display text-xl md:text-2xl font-bold tracking-tight">
                  <span className="text-gradient-cyan">Quantum</span>
                  <span className="text-white">Truth</span>
                </h1>
                <p className="hidden md:block text-xs text-[var(--text-tertiary)] font-mono tracking-wide">
                  PREDICTION MARKET INTELLIGENCE
                </p>
              </div>
            </div>

            {/* Navigation */}
            <nav 
              ref={containerRef}
              className="relative flex items-center gap-1 p-1 rounded-full bg-surface/80 backdrop-blur-sm border border-subtle"
            >
              {/* Active indicator */}
              <motion.div
                className="absolute inset-y-1 rounded-full bg-gradient-to-r from-cyan/20 to-cyan/10 border border-cyan/30"
                initial={false}
                animate={{
                  x: indicatorStyle.x,
                  width: indicatorStyle.width,
                }}
                transition={{ 
                  type: "spring", 
                  stiffness: UI_CONSTANTS.ANIMATION.SPRING_STIFFNESS, 
                  damping: UI_CONSTANTS.ANIMATION.SPRING_DAMPING 
                }}
              />
              
              {tabs.map((tab) => (
                <button
                  key={tab.id}
                  ref={(el) => {
                    tabRefs.current[tab.id] = el;
                  }}
                  onClick={() => setView(tab.id)}
                  className={`relative z-10 flex items-center gap-2 px-4 md:px-5 py-2 rounded-full font-medium transition-all text-sm ${
                    view === tab.id
                      ? "text-cyan"
                      : "text-[var(--text-tertiary)] hover:text-white"
                  }`}
                >
                  <tab.icon className="h-4 w-4" />
                  <span className="hidden sm:inline font-display">{tab.label}</span>
                </button>
              ))}
            </nav>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="relative z-10 mx-auto px-4 sm:px-6 lg:px-8 py-8 md:py-12 max-w-[1800px]">
        <AnimatePresence mode="wait">
          {view === "search" ? (
            <motion.div
              key="search"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.3, ease: [0.23, 1, 0.32, 1] }}
            >
              {/* Hero Section */}
              <div className="text-center mb-10 md:mb-14">
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.1 }}
                >
                  <span className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-cyan-dim border border-cyan/20 text-cyan text-xs font-mono mb-4">
                    <span className="w-1.5 h-1.5 rounded-full bg-cyan animate-pulse-glow" />
                    REAL-TIME MARKET INTELLIGENCE
                  </span>
                </motion.div>
                
                <motion.h2 
                  className="font-display text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight mb-4"
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.15 }}
                >
                  <span className="text-white">What's happening?</span>
                  <br />
                  <span className="text-gradient-cyan">Markets know first.</span>
                </motion.h2>
                
                <motion.p 
                  className="text-[var(--text-secondary)] text-lg max-w-2xl mx-auto"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ delay: 0.2 }}
                >
                  Get live updates on any topic, fact-check claims, or ask what's trending — 
                  powered by prediction markets, news, and social sentiment.
                </motion.p>
              </div>

              {/* Search Box */}
              <div className="max-w-3xl mx-auto mb-12">
                <SearchBox
                  question={question}
                  setQuestion={setQuestion}
                  onSubmit={handleSubmit}
                  loading={loading}
                />
              </div>

              {/* Loading State */}
              <AnimatePresence mode="wait">
                {loading && (
                  <motion.div
                    key="loading"
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.95 }}
                    className="flex flex-col items-center py-16"
                  >
                    {/* Orbital loader */}
                    <div className="relative w-20 h-20">
                      <motion.div
                        className="absolute inset-0 rounded-full border-2 border-cyan/20"
                        animate={{ rotate: 360 }}
                        transition={{ duration: 3, repeat: Infinity, ease: "linear" }}
                      />
                      <motion.div
                        className="absolute inset-2 rounded-full border-2 border-t-cyan border-r-transparent border-b-transparent border-l-transparent"
                        animate={{ rotate: -360 }}
                        transition={{ duration: 1.5, repeat: Infinity, ease: "linear" }}
                      />
                      <motion.div
                        className="absolute inset-0 flex items-center justify-center"
                        animate={{ scale: [1, 1.1, 1] }}
                        transition={{ duration: 2, repeat: Infinity }}
                      >
                        <Zap className="w-6 h-6 text-cyan" />
                      </motion.div>
                    </div>
                    
                    <motion.div
                      className="mt-8 text-center"
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      transition={{ delay: 0.2 }}
                    >
                      <p className="font-display text-white font-semibold text-lg">
                        Gathering intelligence...
                      </p>
                      <p className="text-[var(--text-tertiary)] text-sm mt-1 font-mono">
                        Markets • News • Twitter • Reddit • Kalshi
                      </p>
                    </motion.div>
                  </motion.div>
                )}

                {result && !loading && (
                  <motion.div
                    key="result"
                    initial={{ opacity: 0, y: 30 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -30 }}
                    transition={{ duration: 0.4, ease: [0.23, 1, 0.32, 1] }}
                  >
                    {result.error ? (
                      <motion.div 
                        className="glass-card rounded-xl p-6 border-coral/30 bg-coral-dim"
                        initial={{ scale: 0.95 }}
                        animate={{ scale: 1 }}
                      >
                        <p className="text-coral font-medium">{result.error}</p>
                      </motion.div>
                    ) : (
                      <>
                        {import.meta.env.DEV && (
                          <div className="mb-4 flex justify-end">
                            <button
                              onClick={() => setShowDebug(!showDebug)}
                              className="text-sm text-[var(--text-tertiary)] hover:text-white transition-colors px-3 py-1.5 rounded-lg border border-subtle hover:border-bright font-mono"
                            >
                              {showDebug ? "Hide" : "Show"} Debug
                            </button>
                          </div>
                        )}
                        <ResultCard result={result} showDebug={showDebug} />
                      </>
                    )}
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          ) : view === "dashboard" ? (
            <motion.div
              key="dashboard"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.3, ease: [0.23, 1, 0.32, 1] }}
            >
              <Dashboard />
            </motion.div>
          ) : view === "queries" ? (
            <motion.div
              key="queries"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.3, ease: [0.23, 1, 0.32, 1] }}
            >
              <RecentQueries />
            </motion.div>
          ) : (
            <motion.div
              key="news"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.3, ease: [0.23, 1, 0.32, 1] }}
            >
              <NewsFeed />
            </motion.div>
          )}
        </AnimatePresence>
      </main>
    </div>
  );
}

function App() {
  return (
    <ConvexProvider client={convex}>
      <AppContent />
    </ConvexProvider>
  );
}

export default App;
