import { useAction, useQuery } from "convex/react";
// @ts-ignore generated by convex
import { api } from "../convex/_generated/api";

export default function AuthControls() {
  const status = useQuery(api.auth.getAuthStatus, { provider: "openai", accountId: "default" });
  const disconnect = useAction(api.actions.providerAuth.authDisconnect);

  const convexUrl = import.meta.env.VITE_CONVEX_URL || window.location.origin;

  const onConnect = () => {
    const url = `${convexUrl}/auth/openai/start`;
    window.open(url, "openai-oauth", "popup,width=540,height=700");
  };

  const onDisconnect = async () => {
    await disconnect({ provider: "openai", accountId: "default" });
  };

  return (
    <div className="flex items-center gap-2 text-xs">
      <span className={`px-2 py-1 rounded border ${status?.connected ? "text-emerald-300 border-emerald-700/50 bg-emerald-900/20" : "text-zinc-400 border-zinc-700 bg-zinc-900/40"}`}>
        {status?.connected ? "OpenAI Connected" : "OpenAI Not Connected"}
      </span>
      {status?.connected ? (
        <button
          onClick={onDisconnect}
          className="px-2 py-1 rounded border border-zinc-700 text-zinc-300 hover:text-white hover:border-zinc-500"
        >
          Disconnect
        </button>
      ) : (
        <button
          onClick={onConnect}
          className="px-2 py-1 rounded border border-emerald-700/50 text-emerald-300 hover:text-white hover:border-emerald-500"
        >
          Connect OpenAI
        </button>
      )}
    </div>
  );
}
